[package]
name = "freerdp2"
description = "FreeRDP bindings"
edition = "2021"
version = "0.1.0"
license = "Apache-2.0"

[dependencies]
freerdp2-sys = { version = "0.1", path = "../freerdp2-sys" }
bitflags = "1.3.2"
